### PR TITLE
draft: enable system auth for oracle based connections

### PR DESCRIPTION
**Pull request by wseaton**
Proposed solution for #202

### CODE REVIEW

**Comment by wangxiaoying** [comment]
Hi @wseaton , thanks so much for the PR! I will merge and make an alpha release for this feature to let users test it more conveniently.

**Comment by cmartill** [comment]
What is the release to test it?

**Comment by wangxiaoying** [comment]
> What is the release to test it?

Hi @cmartill , we will have our planned release (0.2.4) today first. Then I will merge this PR and release an alpha version.

**Comment by wangxiaoying** [comment]
Hi @cmartill , `0.2.4-alpha.1` is released. Please feel free to try out.

**Pull request merged**
