### PR TITLE
Feat/pg name support

### PR DESCRIPTION
**Pull request by Jordan-M-Young**
The goal of this PR is to extend support for the Postgres name type requested within the issue: https://github.com/sfu-db/connector-x/issues/501. This issue centers around connectorx panicking when interacting with tables containing a name type.

To solve this, I added:

    a Name type in the various enums in connectorx/src/sources/postgres/typesystem.rs
    a mapping between Name and LargeUtf8 in connectorx/src/transports/postgres_arrow2.rs
    added NAME data to scripts/postgres.sql
    added a test for NAME compatibility with postgres/polars in connectorx/tests/test_polars.rs

### CODE REVIEW

**Comment by Jordan-M-Young** [comment]
@wangxiaoying hope you're well! Would you mind taking a look at this when you have a chance? Thanks!

**Comment by wangxiaoying** [comment]
Hi @Jordan-M-Young , thanks for the PR. It looks good to me for `arrow2/polars`. 

Could you also add this support for `arrow` and `pandas`, basically the transport mapping in `connectorx/src/transports/postgres_arrow.rs` and `connectorx-python/src/pandas/transports/postgres.rs`, as well their corresponding tests? (Looks like #475 is using `pandas` for the result type) 

After this we can merge this. Thanks!

**Comment by MatsMoll** [comment]
Any idea when this will get merged? 😄

**Comment by Jordan-M-Young** [comment]
> Any idea when this will get merged? 😄

Hey @MatsMoll, Things have been busy with my job lately but I should have some time this weekend to finish up the PR!

**Comment by Jordan-M-Young** [comment]
Hey @wangxiaoying I think my latest commit satisfies your requests above. If so would you mind merging?

**Comment by wangxiaoying** [comment]
Thanks @Jordan-M-Young !

**Comment by Jordan-M-Young** [comment]
@wangxiaoying Thank you as always! @MatsMoll shouldn't be long before this is released!

**Comment by MatsMoll** [comment]
Thank you for merging this! Appreciate it @Jordan-M-Young @wangxiaoying

**Pull request merged**
