### PR TITLE
Upgrade to DataFusion 28 and Arrow 43

### LINKED ISSUE #493: Update dependencies to latest versions
#### Describe your feature request

A lot of required and optional dependencies that are mentioned in `connector-x`'s Cargo.toml are due for an update. Listing down some of the important ones,

- Arrow 
- Datafusion
- Polars
- sqlparser

### PR DESCRIPTION
**Pull request by gruuya**
Also upgrade and align with sqlparser 0.35. 

Closes #493.

### CODE REVIEW

**Comment by gruuya** [comment]
@wangxiaoying I have noticed that builds are failing due to hard-coded toolchain versions, which become obsolete after running `cargo update`. First it was:
```
package `constant_time_eq v0.3.0` cannot be built because it requires rustc 1.66.0 or newer, while the currently active rustc version is 1.65.0
```
and when I bumped the version to 1.66.0 it is
```
package `half v2.3.1` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.66.0
```
Any reason not to set this to `stable` (or `nightly` for that matter)?

**Comment by wangxiaoying** [comment]
Hi @gruuya,  thanks for the PR, and sorry for the late reply!

> Any reason not to set this to stable (or nightly for that matter)?

Previously we need to use a specific version, but now I think we can change it to `stable`.

I have a branch [arrow-stream](https://github.com/sfu-db/connector-x/tree/arrow-stream)  that is waiting to merge (pr #536) after sorting out the Conda release. It adds arrow stream as a new destination with different implementation logic and has bumped arrow and datafusion version to 40 and 26.  Is it possible if you can apply your modifications to that?

**Comment by gruuya** [comment]
> I have a branch [arrow-stream](https://github.com/sfu-db/connector-x/tree/arrow-stream) that is waiting to merge (pr #536) after sorting out the Conda release. It adds arrow stream as a new destination with different implementation logic and has bumped arrow and datafusion version to 40 and 26. Is it possible if you can apply your modifications to that?

Oh certainly, I can re-base/open a new PR once that is merged. Or did you have something else in mind?

**Comment by wangxiaoying** [comment]
> Oh certainly, I can re-base/open a new PR once that is merged. Or did you have something else in mind?

I just merged `arrow-stream` branch to main. Can you rebase this one (or reopen a new one if you like) on the current main branch? Thank you!

**Comment by gruuya** [comment]
Closing in favor of #540.

**Pull request closed without merging**
