### PR TITLE
Mssql fixes

### PR DESCRIPTION
**Pull request by Niivii**
Should fix https://github.com/sfu-db/connector-x/issues/678 https://github.com/sfu-db/connector-x/issues/619 https://github.com/sfu-db/connector-x/issues/354 https://github.com/sfu-db/connector-x/issues/560 + a probably a bunch of others

### CODE REVIEW

**Comment by Niivii** [comment]
Ok. Mandatroy disclaimer it's my first week coding in Rust and as I'm on Windows I couldn't make the tests runs because the profiling requires nix. I will setup a wsl or container and dig.

Didn't think UUID bump would break the tests.
@wangxiaoying Or could this just be because I forgot to bump the toml for connectorx-python ? 🤦

**Comment by wangxiaoying** [comment]
Hi @Niivii , thanks for the PR! (sorry for the late reply)

> Or could this just be because I forgot to bump the toml for connectorx-python ?
I just approved the CI running for this PR, let's see whether that's the issue.

Also, if you want to build and test offline on windows, [here](https://github.com/sfu-db/connector-x/blob/main/.github/workflows/release.yml#L160) is the github workflow of how we build the wheel files for windows release. Hope it can be use as a reference.

**Comment by Niivii** [comment]
Thanks a lot @wangxiaoying ! I will have a look and fix the postgres type test. Will probably have to modify it because of the UUID library bumps.

**Comment by Niivii** [comment]
Closing this as a lot of changes has already been taken care of in 0.4.
I will reopen a new simpler PR just for SQL Server named instance issue and the pre login token supports (using_named_connection() + bump of tiberius to 0.9+).

**Pull request closed without merging**
